name: CI-CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t kalash655/visit-counter:${{ github.sha }} -t kalash655/visit-counter:latest .

      - name: Push Docker image
        run: |
          docker push kalash655/visit-counter:${{ github.sha }}
          docker push kalash655/visit-counter:latest

      - name: Deploy to Kubernetes
        run: kubectl set image deployment/app app=kalash655/visit-counter:${{ github.sha }}

      - name: Wait for rollout to complete
        run: kubectl rollout status deployment/app --timeout=90s